### ISSUE TITLE
get_next starts returning the same timestamps after DST switch in Europe

### ISSUE THREAD

**Issue by unterwegi** [taichino/croniter#91]
This example shows the issue:

```
from croniter.croniter import croniter
from datetime import datetime
import pytz

tz = pytz.timezone('Europe/Vienna')

def test_croniter(start_time, repeat=40):
    start_time = tz.localize(start_time)
    print("-" * 100)
    print(f"start_time = {str(start_time)}")
    print("-" * 100)

    test_cron = croniter('30 * * * *', start_time=start_time)
    for i in range(repeat):
        print(test_cron.get_next(datetime))

    print("-" * 100)

# First test: cron timestamps start repeating after the DST change from 03:00 AM back to 02:00 AM
test_croniter(datetime(2017, 10, 28, 10, 9))

# Second test: It get's even weirder when the start_time is at the same day as the DST change,
# because the timestamps start repeating at around 21:00 (i.e. 09:00 PM)
test_croniter(datetime(2017, 10, 29, 0, 5))

# Third test: Here's another test that shows repeating timestamps after a DST change
# that changes the clock from 02:00 AM to 03:00 AM
test_croniter(datetime(2017, 3, 25, 20, 5))
```

It just creates some croniter instances with different start_time values that are all around this year's DST changes in Europe and then repeatedly calls get_next on them and prints the returned datetime objects. 

Just for background information:

Europe always switches from standard time to DST at 02:00 AM (switching to 03:00 AM) on the last Sunday of March (was the 26th this year). 
The switch from DST back to standard time then happens at 03:00 AM (back to 02:00 AM) on the last Sunday of October (was the 29th this year).

The first test_croniter call produces output like this:

```
----------------------------------------------------------------------------------------------------
start_time = 2017-10-28 10:09:00+02:00
----------------------------------------------------------------------------------------------------
2017-10-28 10:30:00+02:00
2017-10-28 11:30:00+02:00
...
2017-10-28 23:30:00+02:00
2017-10-29 00:30:00+02:00
2017-10-29 01:30:00+02:00
2017-10-29 02:30:00+02:00
2017-10-29 01:30:00+01:00
2017-10-29 01:30:00+01:00
2017-10-29 01:30:00+01:00
2017-10-29 01:30:00+01:00
... (stays the same after that)
```
Here's the second one:

```
----------------------------------------------------------------------------------------------------
start_time = 2017-10-29 00:05:00+02:00
----------------------------------------------------------------------------------------------------
2017-10-29 00:30:00+02:00
2017-10-29 01:30:00+02:00
2017-10-29 02:30:00+02:00
2017-10-29 02:30:00+01:00
2017-10-29 03:30:00+01:00
2017-10-29 04:30:00+01:00
...
2017-10-29 20:30:00+01:00
2017-10-29 21:30:00+01:00
2017-10-29 21:30:00+01:00
2017-10-29 21:30:00+01:00
2017-10-29 21:30:00+01:00
... (stays the same after that)
```

And here the third one:

```
----------------------------------------------------------------------------------------------------
start_time = 2017-03-25 20:05:00+01:00
----------------------------------------------------------------------------------------------------
2017-03-25 20:30:00+01:00
2017-03-25 21:30:00+01:00
2017-03-25 22:30:00+01:00
2017-03-25 23:30:00+01:00
2017-03-26 00:30:00+01:00
2017-03-26 01:30:00+01:00
2017-03-26 02:30:00+02:00
2017-03-26 02:30:00+02:00
2017-03-26 02:30:00+02:00
2017-03-26 02:30:00+02:00
... (stays the same after that)
```

This is also not limited to the "Europe/Vienna" time zone. The issue also comes up when using "Europe/Kiev", "Europe/Lisbon", "Europe/London", ...

Tested against croniter 0.3.19

**Comment by kbrose** [comment]
Same with American timezones.

**Comment by chassing** [comment]
I had similar issue on the last weekend (PST)

**Comment by kbrose** [comment]
@unterwegi @chassing 

If you two want to try out the changeset from https://github.com/taichino/croniter/pull/92 I'd appreciate the extra verification.

**Comment by kbrose** [comment]
Is this resolved by the new release (https://pypi.python.org/pypi/croniter/0.3.20)? (https://github.com/taichino/croniter/pull/92)

**Comment by chassing** [comment]
If I'm using @unterwegi test script than I can still see a strange behavior (I'm using "0,30 * * * *" as cron line):


test one - in fall started one day before. we should see 2am twice (see test two):
```
2017-10-29 01:00:00+02:00
2017-10-29 01:30:00+02:00
2017-10-29 02:00:00+02:00
2017-10-29 02:30:00+02:00
2017-10-29 03:00:00+01:00
2017-10-29 03:30:00+01:00
2017-10-29 04:00:00+01:00
2017-10-29 04:30:00+01:00
```

test two - in fall started on the same day. this one looks correct but different to test one:
```
2017-10-29 01:00:00+02:00
2017-10-29 01:30:00+02:00
2017-10-29 02:00:00+02:00
2017-10-29 02:30:00+02:00
2017-10-29 02:00:00+01:00
2017-10-29 02:30:00+01:00
2017-10-29 03:00:00+01:00
2017-10-29 03:30:00+01:00
2017-10-29 04:00:00+01:00
2017-10-29 04:30:00+01:00
```

test three - in spring but day before. looks strange:
```
2017-03-26 01:00:00+01:00
2017-03-26 01:30:00+01:00
2017-03-26 02:00:00+02:00
2017-03-26 01:30:00+01:00
2017-03-26 03:00:00+02:00
2017-03-26 03:30:00+02:00
2017-03-26 04:00:00+02:00
2017-03-26 04:30:00+02:00
```

**Comment by kbrose** [comment]
Hmm, so tests 1 & 2 look correct to me. Am I interpreting that correctly? Test 3 I agree looks strange.

**Comment by chassing** [comment]
test 1 & 2 should have the same output. 2am must be there twice, once with +02 and once with +01. so the output of test 2 is the correct one

**Comment by kiorky** [comment]
#96 is dupped isnt it ?

**Comment by Hopetree** [comment]
when i set the cron string "0 11 4 * mon-wed" ,it get a bad time list
like this test
```
# -*- coding:utf-8 -*-
from datetime import datetime
from croniter import croniter

class MyCroniter():
    def __init__(self,cronstr):
        self.cronstr = cronstr
        self.base_time = datetime.now()

    def get_time_list(self,n):
        itr = croniter(self.cronstr,self.base_time)
        lis = [itr.get_next(datetime).strftime('%F %T') for i in range(n)]
        print(lis)

if __name__ == '__main__':
    TEST = [
        '0 3,6,9 * * *',
        '0 5-12 * * *',
        '*/10 * * * *',
        '0 */2 10 * *',
        '0 0 31 * *',
        '0 11 4 * mon-wed',  # get bad time
        '*/5 5-10,14-20 * 1-5,9-12 1-5'
    ]
    for t in TEST:
        c = MyCroniter(t)
        c.get_time_list(3)
```

results 
```
['2019-07-05 03:00:00', '2019-07-05 06:00:00', '2019-07-05 09:00:00']
['2019-07-05 05:00:00', '2019-07-05 06:00:00', '2019-07-05 07:00:00']
['2019-07-04 15:40:00', '2019-07-04 15:50:00', '2019-07-04 16:00:00']
['2019-07-10 00:00:00', '2019-07-10 02:00:00', '2019-07-10 04:00:00']
['2019-07-31 00:00:00', '2019-08-31 00:00:00', '2019-10-31 00:00:00']
['2019-07-08 11:00:00', '2019-07-09 11:00:00', '2019-07-10 11:00:00']
['2019-09-02 05:00:00', '2019-09-02 05:05:00', '2019-09-02 05:10:00']
```
['2019-07-08 11:00:00', '2019-07-09 11:00:00', '2019-07-10 11:00:00']  this is the bad time, the day should be 4

**Comment by kiorky** [comment]
dup #90
